#!/bin/bash
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $thisdir/source
# Install
apt-get install apt-transport-https
apt-get install git
cd ~/
git clone ${newsreader_installer_url}
cd ${newsreader_installer_dir}
./install
cd ~/newsreader_installer_url}
cd ${newsreader_installer_dir}/test
./testit
