#!/bin/bash
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $thisdir/source
cp ${thisdir}/nrkey ~/
# Install
apt-get -y update
apt-get -y upgrade
apt-get -y install apt-transport-https
apt-get -y install git lsof
apt-get -y clean
cd ~/
git clone ${newsreader_installer_url}
cd ${newsreader_installer_dir}

readlink -f ./install 
#cd ~/${newsreader_installer_dir}/test
#./testit
