#!/bin/bash
# Install
apt-get install apt-transport-https
apt-get install git
cd ~/
git clone ${newsreader_installer_url}
cd ${newsreader_installer_dir}
./install
cd ~/newsreader_installer_url}
cd ${newsreader_installer_dir}/test
./testit
